# Generated by Django 2.2.6 on 2019-11-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191113_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point_relate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
            ],
        ),
    ]
