# Generated by Django 2.2.6 on 2019-12-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0011_auto_20191201_1658'),
        ('login', '0011_remove_review_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserv.Menu'),
        ),
    ]
