# Generated by Django 2.2.6 on 2019-12-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_review_menu'),
        ('login', '0013_normaluser_point'),
    ]

    operations = [
    ]
