# Generated by Django 2.2.6 on 2019-12-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_merge_20191201_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
