# Generated by Django 2.2.6 on 2019-11-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0007_relate_reserv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_user_reservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reserv.Reservation')),
                ('phone_number', models.CharField(default='None', max_length=15)),
                ('serial_number', models.CharField(default='T2Z9CYC2', max_length=15)),
                ('user_name', models.CharField(default='홍길동', max_length=20)),
            ],
            bases=('reserv.reservation',),
        ),
        migrations.AlterField(
            model_name='relate_reserv',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
