# Generated by Django 2.2.6 on 2019-11-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0008_auto_20191127_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_user_reservation',
            name='serial_number',
            field=models.CharField(default='CHOZWA57', max_length=15),
        ),
    ]
