# Generated by Django 2.2.6 on 2019-12-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0010_auto_20191201_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_user_reservation',
            name='serial_number',
            field=models.CharField(default='66WQD32E', max_length=15),
        ),
    ]
