# Generated by Django 2.2.6 on 2019-12-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0011_auto_20191201_1658'),
        ('reserv', '0008_reservation_ischeck'),
    ]

    operations = [
    ]
