# Generated by Django 2.2.7 on 2019-12-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0013_auto_20191201_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_user_reservation',
            name='serial_number',
            field=models.CharField(default='8IO4IYPN', max_length=15),
        ),
    ]
