# Generated by Django 2.2.6 on 2019-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0014_auto_20191202_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_user_reservation',
            name='serial_number',
            field=models.CharField(default='XM6JV5WU', max_length=15),
        ),
    ]
